//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksMVC.DomainModel.BookWcfService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthorServiceModel", Namespace="http://schemas.datacontract.org/2004/07/BooksWcfServices")]
    [System.SerializableAttribute()]
    public partial class AuthorServiceModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AuthorIDField;
        
        private string AuthorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BooksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AuthorID {
            get {
                return this.AuthorIDField;
            }
            set {
                if ((this.AuthorIDField.Equals(value) != true)) {
                    this.AuthorIDField = value;
                    this.RaisePropertyChanged("AuthorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AuthorName {
            get {
                return this.AuthorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorNameField, value) != true)) {
                    this.AuthorNameField = value;
                    this.RaisePropertyChanged("AuthorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Books {
            get {
                return this.BooksField;
            }
            set {
                if ((object.ReferenceEquals(this.BooksField, value) != true)) {
                    this.BooksField = value;
                    this.RaisePropertyChanged("Books");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookServiceModel", Namespace="http://schemas.datacontract.org/2004/07/BooksWcfServices")]
    [System.SerializableAttribute()]
    public partial class BookServiceModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private BooksMVC.DomainModel.BookWcfService.AuthorServiceModel[] AuthorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BookIDField;
        
        private string BookNameField;
        
        private string[] SelectedAuthorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public BooksMVC.DomainModel.BookWcfService.AuthorServiceModel[] Authors {
            get {
                return this.AuthorsField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorsField, value) != true)) {
                    this.AuthorsField = value;
                    this.RaisePropertyChanged("Authors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BookID {
            get {
                return this.BookIDField;
            }
            set {
                if ((this.BookIDField.Equals(value) != true)) {
                    this.BookIDField = value;
                    this.RaisePropertyChanged("BookID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string BookName {
            get {
                return this.BookNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BookNameField, value) != true)) {
                    this.BookNameField = value;
                    this.RaisePropertyChanged("BookName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string[] SelectedAuthors {
            get {
                return this.SelectedAuthorsField;
            }
            set {
                if ((object.ReferenceEquals(this.SelectedAuthorsField, value) != true)) {
                    this.SelectedAuthorsField = value;
                    this.RaisePropertyChanged("SelectedAuthors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookWcfService.IBookWcfService")]
    public interface IBookWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookWcfService/GetAuthors", ReplyAction="http://tempuri.org/IBookWcfService/GetAuthorsResponse")]
        BooksMVC.DomainModel.BookWcfService.AuthorServiceModel[] GetAuthors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookWcfService/GetAuthors", ReplyAction="http://tempuri.org/IBookWcfService/GetAuthorsResponse")]
        System.Threading.Tasks.Task<BooksMVC.DomainModel.BookWcfService.AuthorServiceModel[]> GetAuthorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookWcfService/GetBooks", ReplyAction="http://tempuri.org/IBookWcfService/GetBooksResponse")]
        BooksMVC.DomainModel.BookWcfService.BookServiceModel[] GetBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookWcfService/GetBooks", ReplyAction="http://tempuri.org/IBookWcfService/GetBooksResponse")]
        System.Threading.Tasks.Task<BooksMVC.DomainModel.BookWcfService.BookServiceModel[]> GetBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookWcfService/GetBook", ReplyAction="http://tempuri.org/IBookWcfService/GetBookResponse")]
        BooksMVC.DomainModel.BookWcfService.BookServiceModel GetBook(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookWcfService/GetBook", ReplyAction="http://tempuri.org/IBookWcfService/GetBookResponse")]
        System.Threading.Tasks.Task<BooksMVC.DomainModel.BookWcfService.BookServiceModel> GetBookAsync(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookWcfService/CreateBook", ReplyAction="http://tempuri.org/IBookWcfService/CreateBookResponse")]
        BooksMVC.DomainModel.BookWcfService.BookServiceModel CreateBook(BooksMVC.DomainModel.BookWcfService.BookServiceModel vmBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookWcfService/CreateBook", ReplyAction="http://tempuri.org/IBookWcfService/CreateBookResponse")]
        System.Threading.Tasks.Task<BooksMVC.DomainModel.BookWcfService.BookServiceModel> CreateBookAsync(BooksMVC.DomainModel.BookWcfService.BookServiceModel vmBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookWcfService/EditBook", ReplyAction="http://tempuri.org/IBookWcfService/EditBookResponse")]
        BooksMVC.DomainModel.BookWcfService.BookServiceModel EditBook(BooksMVC.DomainModel.BookWcfService.BookServiceModel vmBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookWcfService/EditBook", ReplyAction="http://tempuri.org/IBookWcfService/EditBookResponse")]
        System.Threading.Tasks.Task<BooksMVC.DomainModel.BookWcfService.BookServiceModel> EditBookAsync(BooksMVC.DomainModel.BookWcfService.BookServiceModel vmBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookWcfService/RemoveBook", ReplyAction="http://tempuri.org/IBookWcfService/RemoveBookResponse")]
        void RemoveBook(BooksMVC.DomainModel.BookWcfService.BookServiceModel vmBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookWcfService/RemoveBook", ReplyAction="http://tempuri.org/IBookWcfService/RemoveBookResponse")]
        System.Threading.Tasks.Task RemoveBookAsync(BooksMVC.DomainModel.BookWcfService.BookServiceModel vmBook);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookWcfServiceChannel : BooksMVC.DomainModel.BookWcfService.IBookWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookWcfServiceClient : System.ServiceModel.ClientBase<BooksMVC.DomainModel.BookWcfService.IBookWcfService>, BooksMVC.DomainModel.BookWcfService.IBookWcfService {
        
        public BookWcfServiceClient() {
        }
        
        public BookWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BooksMVC.DomainModel.BookWcfService.AuthorServiceModel[] GetAuthors() {
            return base.Channel.GetAuthors();
        }
        
        public System.Threading.Tasks.Task<BooksMVC.DomainModel.BookWcfService.AuthorServiceModel[]> GetAuthorsAsync() {
            return base.Channel.GetAuthorsAsync();
        }
        
        public BooksMVC.DomainModel.BookWcfService.BookServiceModel[] GetBooks() {
            return base.Channel.GetBooks();
        }
        
        public System.Threading.Tasks.Task<BooksMVC.DomainModel.BookWcfService.BookServiceModel[]> GetBooksAsync() {
            return base.Channel.GetBooksAsync();
        }
        
        public BooksMVC.DomainModel.BookWcfService.BookServiceModel GetBook(int bookId) {
            return base.Channel.GetBook(bookId);
        }
        
        public System.Threading.Tasks.Task<BooksMVC.DomainModel.BookWcfService.BookServiceModel> GetBookAsync(int bookId) {
            return base.Channel.GetBookAsync(bookId);
        }
        
        public BooksMVC.DomainModel.BookWcfService.BookServiceModel CreateBook(BooksMVC.DomainModel.BookWcfService.BookServiceModel vmBook) {
            return base.Channel.CreateBook(vmBook);
        }
        
        public System.Threading.Tasks.Task<BooksMVC.DomainModel.BookWcfService.BookServiceModel> CreateBookAsync(BooksMVC.DomainModel.BookWcfService.BookServiceModel vmBook) {
            return base.Channel.CreateBookAsync(vmBook);
        }
        
        public BooksMVC.DomainModel.BookWcfService.BookServiceModel EditBook(BooksMVC.DomainModel.BookWcfService.BookServiceModel vmBook) {
            return base.Channel.EditBook(vmBook);
        }
        
        public System.Threading.Tasks.Task<BooksMVC.DomainModel.BookWcfService.BookServiceModel> EditBookAsync(BooksMVC.DomainModel.BookWcfService.BookServiceModel vmBook) {
            return base.Channel.EditBookAsync(vmBook);
        }
        
        public void RemoveBook(BooksMVC.DomainModel.BookWcfService.BookServiceModel vmBook) {
            base.Channel.RemoveBook(vmBook);
        }
        
        public System.Threading.Tasks.Task RemoveBookAsync(BooksMVC.DomainModel.BookWcfService.BookServiceModel vmBook) {
            return base.Channel.RemoveBookAsync(vmBook);
        }
    }
}
