//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace panasyukva_apriorit_booksmvc.AuthorWcfService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthorServiceModel", Namespace="http://schemas.datacontract.org/2004/07/BooksWcfServices")]
    [System.SerializableAttribute()]
    public partial class AuthorServiceModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AuthorIDField;
        
        private string AuthorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BooksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AuthorID {
            get {
                return this.AuthorIDField;
            }
            set {
                if ((this.AuthorIDField.Equals(value) != true)) {
                    this.AuthorIDField = value;
                    this.RaisePropertyChanged("AuthorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AuthorName {
            get {
                return this.AuthorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorNameField, value) != true)) {
                    this.AuthorNameField = value;
                    this.RaisePropertyChanged("AuthorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Books {
            get {
                return this.BooksField;
            }
            set {
                if ((object.ReferenceEquals(this.BooksField, value) != true)) {
                    this.BooksField = value;
                    this.RaisePropertyChanged("Books");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthorWcfService.IAuthorWcfService")]
    public interface IAuthorWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorWcfService/GetAuthor", ReplyAction="http://tempuri.org/IAuthorWcfService/GetAuthorResponse")]
        panasyukva_apriorit_booksmvc.AuthorWcfService.AuthorServiceModel GetAuthor(int authorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorWcfService/GetAuthor", ReplyAction="http://tempuri.org/IAuthorWcfService/GetAuthorResponse")]
        System.Threading.Tasks.Task<panasyukva_apriorit_booksmvc.AuthorWcfService.AuthorServiceModel> GetAuthorAsync(int authorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorWcfService/CreateAuthor", ReplyAction="http://tempuri.org/IAuthorWcfService/CreateAuthorResponse")]
        panasyukva_apriorit_booksmvc.AuthorWcfService.AuthorServiceModel CreateAuthor(panasyukva_apriorit_booksmvc.AuthorWcfService.AuthorServiceModel vmAuthor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorWcfService/CreateAuthor", ReplyAction="http://tempuri.org/IAuthorWcfService/CreateAuthorResponse")]
        System.Threading.Tasks.Task<panasyukva_apriorit_booksmvc.AuthorWcfService.AuthorServiceModel> CreateAuthorAsync(panasyukva_apriorit_booksmvc.AuthorWcfService.AuthorServiceModel vmAuthor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorWcfService/EditAuthor", ReplyAction="http://tempuri.org/IAuthorWcfService/EditAuthorResponse")]
        panasyukva_apriorit_booksmvc.AuthorWcfService.AuthorServiceModel EditAuthor(panasyukva_apriorit_booksmvc.AuthorWcfService.AuthorServiceModel vmAuthor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorWcfService/EditAuthor", ReplyAction="http://tempuri.org/IAuthorWcfService/EditAuthorResponse")]
        System.Threading.Tasks.Task<panasyukva_apriorit_booksmvc.AuthorWcfService.AuthorServiceModel> EditAuthorAsync(panasyukva_apriorit_booksmvc.AuthorWcfService.AuthorServiceModel vmAuthor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthorWcfServiceChannel : panasyukva_apriorit_booksmvc.AuthorWcfService.IAuthorWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthorWcfServiceClient : System.ServiceModel.ClientBase<panasyukva_apriorit_booksmvc.AuthorWcfService.IAuthorWcfService>, panasyukva_apriorit_booksmvc.AuthorWcfService.IAuthorWcfService {
        
        public AuthorWcfServiceClient() {
        }
        
        public AuthorWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthorWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public panasyukva_apriorit_booksmvc.AuthorWcfService.AuthorServiceModel GetAuthor(int authorId) {
            return base.Channel.GetAuthor(authorId);
        }
        
        public System.Threading.Tasks.Task<panasyukva_apriorit_booksmvc.AuthorWcfService.AuthorServiceModel> GetAuthorAsync(int authorId) {
            return base.Channel.GetAuthorAsync(authorId);
        }
        
        public panasyukva_apriorit_booksmvc.AuthorWcfService.AuthorServiceModel CreateAuthor(panasyukva_apriorit_booksmvc.AuthorWcfService.AuthorServiceModel vmAuthor) {
            return base.Channel.CreateAuthor(vmAuthor);
        }
        
        public System.Threading.Tasks.Task<panasyukva_apriorit_booksmvc.AuthorWcfService.AuthorServiceModel> CreateAuthorAsync(panasyukva_apriorit_booksmvc.AuthorWcfService.AuthorServiceModel vmAuthor) {
            return base.Channel.CreateAuthorAsync(vmAuthor);
        }
        
        public panasyukva_apriorit_booksmvc.AuthorWcfService.AuthorServiceModel EditAuthor(panasyukva_apriorit_booksmvc.AuthorWcfService.AuthorServiceModel vmAuthor) {
            return base.Channel.EditAuthor(vmAuthor);
        }
        
        public System.Threading.Tasks.Task<panasyukva_apriorit_booksmvc.AuthorWcfService.AuthorServiceModel> EditAuthorAsync(panasyukva_apriorit_booksmvc.AuthorWcfService.AuthorServiceModel vmAuthor) {
            return base.Channel.EditAuthorAsync(vmAuthor);
        }
    }
}
